In [1]:
import numpy as np
import math
import pandas 
import random 
import time
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing

In [2]:
dataframe = pandas.read_csv("energy_efficiency_data.csv")

dataframe.columns = ['relative_compactness', 'surface_area', 
                     'wall_area', 'roof_area', 'overall_height', 
                     'orientation', 'glazing_area', 
                     'glazing_area_distribution', 'heating_load', 
                     'cooling_load']

In [3]:
print(dataframe.head())

   relative_compactness  surface_area  wall_area  roof_area  overall_height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.90         563.5      318.5     122.50             7.0   
4                  0.90         563.5      318.5     122.50             7.0   

   orientation  glazing_area  glazing_area_distribution  heating_load  \
0          2.0           0.0                        0.0         15.55   
1          4.0           0.0                        0.0         15.55   
2          5.0           0.0                        0.0         15.55   
3          2.0           0.0                        0.0         20.84   
4          3.0           0.0                        0.0         21.46   

   cooling_load  
0         21.33  
1         21.33  
2         21.33  
3         28.2

In [4]:
print(dataframe.describe())

       relative_compactness  surface_area   wall_area   roof_area  \
count            768.000000    768.000000  768.000000  768.000000   
mean               0.764167    671.708333  318.500000  176.604167   
std                0.105777     88.086116   43.626481   45.165950   
min                0.620000    514.500000  245.000000  110.250000   
25%                0.682500    606.375000  294.000000  140.875000   
50%                0.750000    673.750000  318.500000  183.750000   
75%                0.830000    741.125000  343.000000  220.500000   
max                0.980000    808.500000  416.500000  220.500000   

       overall_height  orientation  glazing_area  glazing_area_distribution  \
count       768.00000   768.000000    768.000000                  768.00000   
mean          5.25000     3.500000      0.234375                    2.81250   
std           1.75114     1.118763      0.133221                    1.55096   
min           3.50000     2.000000      0.000000              

In [5]:
print("Shape:", dataframe.shape)

Shape: (768, 10)


In [6]:
print("Data Types:", dataframe.dtypes)

Data Types: relative_compactness         float64
surface_area                 float64
wall_area                    float64
roof_area                    float64
overall_height               float64
orientation                  float64
glazing_area                 float64
glazing_area_distribution    float64
heating_load                 float64
cooling_load                 float64
dtype: object


In [7]:
print("Correlation:", dataframe.corr(method='pearson'))

Correlation:                            relative_compactness  surface_area     wall_area  \
relative_compactness               1.000000e+00 -9.919015e-01 -2.037817e-01   
surface_area                      -9.919015e-01  1.000000e+00  1.955016e-01   
wall_area                         -2.037817e-01  1.955016e-01  1.000000e+00   
roof_area                         -8.688234e-01  8.807195e-01 -2.923165e-01   
overall_height                     8.277473e-01 -8.581477e-01  2.809757e-01   
orientation                        1.712426e-17  1.203260e-17  0.000000e+00   
glazing_area                      -3.209966e-18  3.631399e-17  1.036064e-17   
glazing_area_distribution          2.161659e-17 -2.419423e-16  0.000000e+00   
heating_load                       6.222722e-01 -6.581202e-01  4.556712e-01   
cooling_load                       6.343391e-01 -6.729989e-01  4.271170e-01   

                              roof_area  overall_height   orientation  \
relative_compactness      -8.688234e-01    8

In [8]:
print(dataframe.values)

[[9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 [9.800e-01 5.145e+02 2.940e+02 ... 0.000e+00 1.555e+01 2.133e+01]
 ...
 [6.600e-01 7.595e+02 3.185e+02 ... 5.000e+00 1.492e+01 1.755e+01]
 [6.400e-01 7.840e+02 3.430e+02 ... 5.000e+00 1.819e+01 2.021e+01]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 1.648e+01 1.661e+01]]


In [9]:
#shuffle
dataset = np.array(dataframe.values)
dataset_shuf = []
index_shuf = list(range(len(dataset)))
random.shuffle(index_shuf)
for i in index_shuf:
    dataset_shuf.append(dataset[i,:])   
dataset_shuf = np.array(dataset_shuf)
dataset_shuf.reshape(768,10)

array([[6.400e-01, 7.840e+02, 3.430e+02, ..., 4.000e+00, 1.699e+01,
        1.965e+01],
       [6.900e-01, 7.350e+02, 2.940e+02, ..., 1.000e+00, 1.272e+01,
        1.578e+01],
       [7.900e-01, 6.370e+02, 3.430e+02, ..., 3.000e+00, 3.697e+01,
        3.510e+01],
       ...,
       [7.600e-01, 6.615e+02, 4.165e+02, ..., 1.000e+00, 3.696e+01,
        3.685e+01],
       [7.600e-01, 6.615e+02, 4.165e+02, ..., 2.000e+00, 4.078e+01,
        3.948e+01],
       [6.900e-01, 7.350e+02, 2.940e+02, ..., 3.000e+00, 1.116e+01,
        1.427e+01]])

In [10]:
X_train = dataset_shuf[:576,0:8]
Y_train = dataset_shuf[:576,8:9]
X_train.reshape(576,8)
Y_train.reshape(576,1)

X_test = dataset_shuf[576:,0:8]
Y_test = dataset_shuf[576:,8:9]
X_test.reshape(192,8)
Y_test.reshape(192,1)

array([[14.32],
       [12.47],
       [14.32],
       [12.33],
       [14.7 ],
       [41.67],
       [17.11],
       [14.19],
       [28.31],
       [29.09],
       [ 8.6 ],
       [29.6 ],
       [14.48],
       [24.17],
       [18.48],
       [15.23],
       [28.15],
       [12.19],
       [12.93],
       [12.27],
       [42.08],
       [25.27],
       [37.03],
       [27.02],
       [24.32],
       [15.23],
       [15.4 ],
       [43.1 ],
       [11.22],
       [ 6.79],
       [ 8.5 ],
       [12.93],
       [28.61],
       [41.92],
       [25.17],
       [19.36],
       [36.45],
       [36.26],
       [29.92],
       [24.63],
       [15.41],
       [32.94],
       [11.67],
       [15.42],
       [12.88],
       [15.55],
       [11.44],
       [32.33],
       [29.83],
       [32.74],
       [32.33],
       [14.17],
       [11.16],
       [37.24],
       [16.93],
       [26.45],
       [14.51],
       [12.32],
       [14.51],
       [32.23],
       [24.29],
       [35.48],
       [

In [11]:
#one-hot
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [5,7])],remainder='passthrough')
X_train = np.array(transformer.fit_transform(X_train), dtype=np.float)

X_test = np.array(transformer.fit_transform(X_test), dtype=np.float)



In [12]:
pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9    10     11     12  \
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.64  784.0  343.0   
1    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.69  735.0  294.0   
2    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.79  637.0  343.0   
3    0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.76  661.5  416.5   
4    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.71  710.5  269.5   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...    ...    ...   
571  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.71  710.5  269.5   
572  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.90  563.5  318.5   
573  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.76  661.5  416.5   
574  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.98  514.5  294.0   
575  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.98  514.5  294.0   

         13   14    15  
0    220.50  3.5  0.25  
1    220.50  3.5  0.25  
2    147.00  7.0  0.10  
3    122.50  7.0  0.25  
4    220.50  3.5  0.10  
..      ...  ...   ...  
571  220.50  3.5  0.00  
572  122.50  7.0  0.10  
573  122.50  7.0  0.25  
574  110.25  7.0  0.40  
575  110.25  7.0  0.10  

[576 rows x 16 columns]

In [13]:
#標準化
X_scaled = np.copy(X_train[:,10:16])
X_scaled2 = np.copy(X_test[:,10:16])

scaler = preprocessing.StandardScaler().fit(X_scaled)

X_scaled = scaler.transform(X_scaled)
X_scaled2 = scaler.transform(X_scaled2)


In [14]:
X_train = np.copy(X_train[:,0:10])
X_test = np.copy(X_test[:,0:10])
X_train = np.append(X_train, X_scaled, axis = 1)
X_test = np.append(X_test, X_scaled2, axis = 1)

pandas.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9        10        11  \
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -1.175630  1.276735   
1    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.706356  0.723803   
2    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.232193 -0.382061   
3    0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.049372 -0.105595   
4    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -0.518646  0.447337   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...       ...   
571  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 -0.518646  0.447337   
572  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.264597 -1.211458   
573  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 -0.049372 -0.105595   
574  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  2.015436 -1.764390   
575  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  2.015436 -1.764390   

           12        13        14        15  
0    0.556412  0.982348 -1.010471  0.115338  
1   -0.568126  0.982348 -1.010471  0.115338  
2    0.556412 -0.642051  0.989637 -1.010678  
3    2.243221 -1.183518  0.989637  0.115338  
4   -1.130396  0.982348 -1.010471 -1.010678  
..        ...       ...       ...       ...  
571 -1.130396  0.982348 -1.010471 -1.761355  
572 -0.005857 -1.183518  0.989637 -1.010678  
573  2.243221 -1.183518  0.989637  0.115338  
574 -0.568126 -1.454251  0.989637  1.241355  
575 -0.568126 -1.454251  0.989637 -1.010678  

[576 rows x 16 columns]

In [15]:
#define weight:

#16 for hidden layer1
#64 for hidden layer2
#64 for hidden layer3
#64 for hidden layer4
#64 for hidden layer5
#8 for output layer6

weight_hidden = np.random.random((16,64))-0.5
weight_hidden2 = np.random.random((64,64))-0.5
weight_hidden3 = np.random.random((64,64))-0.5
weight_hidden4 = np.random.random((64,64))-0.5
weight_hidden5 = np.random.random((64,8))-0.5
weight_output = np.random.random((8,1))-0.5
lr = 0.00003

bias = 0.01
bias1 = 0.01
bias2 = 0.01
bias3 = 0.01
bias4 = 0.01
bias5 = 0.01


In [16]:
def ReLU(x) :
    return x * (x > 0) + 0.01 * x * (x <= 0)

def ReLU_der(x) :
    return 1 * (x > 0) + 0.01 * (x <= 0)

def limit(x) :  
    while(np.max(x) > 0.1 or np.min(x) < -0.1) : 
            x /= 10
    return x        

In [17]:
epochtimes = 20000
mini_batch = 16
bestloss1 = 1e30 #Mini Batch Loss
preloss = 1e30   #decay the learning rate
start = time.time()

for epoch in range(epochtimes):
    X_train_random = []
    Y_train_random = []
    for i in range(mini_batch):
        rindex = random.randint(0,len(X_train)-1)
        X_train_random.append(X_train[rindex,:])
        Y_train_random.append(Y_train[rindex,:])
    X_train_random = np.array(X_train_random)
    Y_train_random = np.array(Y_train_random)
    
    
        
    input_hidden = np.dot(X_train_random, weight_hidden) + bias
    output_hidden = ReLU(input_hidden)
    
    input_hidden2 = np.dot(output_hidden, weight_hidden2) + bias1
    output_hidden2 = ReLU(input_hidden2)
    input_hidden3 = np.dot(output_hidden2, weight_hidden3) + bias2
    output_hidden3 = ReLU(input_hidden3)
    input_hidden4 = np.dot(output_hidden3, weight_hidden4) + bias3
    output_hidden4 = ReLU(input_hidden4)
    input_hidden5 = np.dot(output_hidden4, weight_hidden5) + bias4
    output_hidden5 = ReLU(input_hidden5)
    input_op = np.dot(output_hidden5, weight_output) + bias5
    output_op = ReLU(input_op)
    
    
    
    #==========================================
    
    derror_douto = output_op - Y_train_random
    douto_dino = ReLU_der(input_op)
    dino_dwo = output_hidden5      
    derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
    derror_dbias5 = derror_douto * douto_dino
    
    #==========================================
    
    derror_dino = derror_douto * douto_dino
    dino_douth5 = weight_output
    derror_douth5 = np.dot(derror_dino, dino_douth5.T)
    douth5_dinh5 = ReLU_der(input_hidden5)
    dinh5_dwh5 = output_hidden4
    derror_dwh5 = np.dot(dinh5_dwh5.T, douth5_dinh5 * derror_douth5)
    derror_dbias4 = douth5_dinh5 * derror_douth5
    
    #==========================================
    
    derror_dinh5 = derror_douth5 * douth5_dinh5
    dinh5_douth4 = weight_hidden5
    derror_douth4 = np.dot(derror_dinh5, dinh5_douth4.T)
    douth4_dinh4 = ReLU_der(input_hidden4)
    dinh4_dwh4 = output_hidden3
    derror_dwh4 = np.dot(dinh4_dwh4.T, douth4_dinh4 * derror_douth4)
    derror_dbias3 = douth4_dinh4 * derror_douth4
    
    #==========================================
    
    derror_dinh4 = derror_douth4 * douth4_dinh4
    dinh4_douth3 = weight_hidden4
    derror_douth3 = np.dot(derror_dinh4, dinh4_douth3.T)
    douth3_dinh3 = ReLU_der(input_hidden3)
    dinh3_dwh3 = output_hidden2
    derror_dwh3 = np.dot(dinh3_dwh3.T, douth3_dinh3 * derror_douth3)
    derror_dbias2 = douth3_dinh3 * derror_douth3
    
    #==========================================
    
    derror_dinh3 = derror_douth3 * douth3_dinh3
    dinh3_douth2 = weight_hidden3
    derror_douth2 = np.dot(derror_dinh3, dinh3_douth2.T)
    douth2_dinh2 = ReLU_der(input_hidden2)
    dinh2_dwh2 = output_hidden
    derror_dwh2 = np.dot(dinh2_dwh2.T, douth2_dinh2 * derror_douth2)
    derror_dbias1 = douth2_dinh2 * derror_douth2
    
    #==========================================
    
    derror_dinh2 = derror_douth2 * douth2_dinh2
    dinh2_douth = weight_hidden2
    derror_douth = np.dot(derror_dinh2, dinh2_douth.T)
    douth_dinh = ReLU_der(input_hidden)
    dinh_dwh = X_train_random
    derror_dwh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
    derror_dbias = douth_dinh * derror_douth
    
    #==========================================
       
    
    
    weight_hidden -= limit(lr * derror_dwh)
    weight_hidden2 -= limit(lr * derror_dwh2)
    weight_hidden3 -= limit(lr * derror_dwh3)
    weight_hidden4 -= limit(lr * derror_dwh4)
    weight_hidden5 -= limit(lr * derror_dwh5)
    weight_output -= limit(lr * derror_dwo)
    
    bias -= lr * derror_dbias.sum()/np.size(derror_dbias)
    bias1 -= lr * derror_dbias1.sum()/np.size(derror_dbias1)
    bias2 -= lr * derror_dbias2.sum()/np.size(derror_dbias2)
    bias3 -= lr * derror_dbias3.sum()/np.size(derror_dbias3)
    bias4 -= lr * derror_dbias4.sum()/np.size(derror_dbias4)
    bias5 -= lr * derror_dbias5.sum()/np.size(derror_dbias5)
    
    error_out = ((1 / 2) * (np.power((output_op - Y_train_random), 2)))
    #print(error_out.sum())
    
        
        
    #calulate error 
    if epoch % 200 == 0 : 
        input_hidden = np.dot(X_train, weight_hidden) + bias
        output_hidden = ReLU(input_hidden)
        input_hidden2 = np.dot(output_hidden, weight_hidden2) + bias1
        output_hidden2 = ReLU(input_hidden2)
        input_hidden3 = np.dot(output_hidden2, weight_hidden3) + bias2
        output_hidden3 = ReLU(input_hidden3)
        input_hidden4 = np.dot(output_hidden3, weight_hidden4) + bias3
        output_hidden4 = ReLU(input_hidden4)
        input_hidden5 = np.dot(output_hidden4, weight_hidden5) + bias4
        output_hidden5 = ReLU(input_hidden5)
        input_op = np.dot(output_hidden5, weight_output)+ bias5
        output_op = ReLU(input_op)
        error_out = ((1 / 2) * (np.power((output_op - Y_train), 2)))
        
   
        #set decay for learning rate
        if error_out.sum() > preloss :
            lr *= 0.9
            
        preloss = error_out.sum()  
       
        
        print('now training ',epoch*100/epochtimes,'%')
        print(error_out.sum())
        #print(error_out)
        #print('\n',lr * derror_dwh,'\n', lr * derror_dwo,'\n')
        
       
        #print(derror_wh, derror_wo)



end = time.time()

now training  0.0 %
147242.1440786899
now training  1.0 %
6943.548862748748
now training  2.0 %
4009.1726939054743
now training  3.0 %
5269.271847589967
now training  4.0 %
11995.954611571768
now training  5.0 %
3530.091990043804
now training  6.0 %
32406.98745752313
now training  7.0 %
6064.457835086025
now training  8.0 %
9640.514877673511
now training  9.0 %
54078.130167821306
now training  10.0 %
2462.058568904212
now training  11.0 %
4740.252895438203
now training  12.0 %
5795.737830035125
now training  13.0 %
2626.8867343242937
now training  14.0 %
8160.9845925256195
now training  15.0 %
2222.5808895500804
now training  16.0 %
870.1097760692048
now training  17.0 %
5059.811606244582
now training  18.0 %
31491.47559357011
now training  19.0 %
366.3654099109111
now training  20.0 %
144.81129913760782
now training  21.0 %
122.91936214546033
now training  22.0 %
152.57067723074573
now training  23.0 %
2052.757022399478
now training  24.0 %
2406.3482439244503
now training  25.0 %
2256

In [18]:
input_hidden = np.dot(X_train, weight_hidden) 
output_hidden = ReLU(input_hidden)
input_hidden2 = np.dot(output_hidden, weight_hidden2) 
output_hidden2 = ReLU(input_hidden2)
input_hidden3 = np.dot(output_hidden2, weight_hidden3) 
output_hidden3 = ReLU(input_hidden3)
input_hidden4 = np.dot(output_hidden3, weight_hidden4) 
output_hidden4 = ReLU(input_hidden4)
input_hidden5 = np.dot(output_hidden4, weight_hidden5) 
output_hidden5 = ReLU(input_hidden5)
input_op = np.dot(output_hidden5, weight_output)
output_op = ReLU(input_op)
error_out = ((1 / len(Y_train)) * (np.power((output_op - Y_train), 2)))

print('result: ')
print(error_out.sum())

result: 
0.5640121644129117


In [19]:
single_point = np.array(X_train)
result1 = np.dot(single_point, weight_hidden) + bias
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2) + bias1
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3) + bias2
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4) + bias3
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5) + bias4
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output) + bias5
result12 = ReLU(result11)
#print(result12)
#print(Y_train_random)
error_out = ((1/len(Y_train)) * (np.power((result12 - Y_train), 2)))
#print(error_out)
print(error_out.sum())

0.008148960865549858


In [20]:
print("bias:",bias )
print("bias1:",bias1 )
print("bias2:",bias2 )
print("bias3:",bias3 )
print("bias4:",bias4 )
print("bias5:",bias5 )

bias: -0.03240484507289045
bias1: -0.004761595449664898
bias2: 0.004431355899370165
bias3: 0.008502546355005037
bias4: 0.010209785931663941
bias5: 0.03950303995822389


In [21]:
single_point = np.array(X_test)
result1 = np.dot(single_point, weight_hidden)
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2)
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3)
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4)
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5)
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output)
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[15.69072482]
 [12.89256762]
 [14.53313789]
 [13.44844731]
 [15.16067247]
 [49.95913325]
 [17.86312159]
 [13.70998182]
 [28.90299878]
 [28.75756888]
 [11.21975811]
 [31.08685275]
 [15.54714335]
 [22.63671629]
 [20.0823644 ]
 [15.2116726 ]
 [27.95661748]
 [12.37663509]
 [13.96221039]
 [12.60752525]
 [39.81923355]
 [25.27810503]
 [35.61039796]
 [28.97180865]
 [24.10390633]
 [15.33155159]
 [16.61102882]
 [49.60977222]
 [11.40917586]
 [ 6.99896178]
 [11.10326599]
 [15.80427729]
 [27.16401281]
 [44.61563896]
 [27.34882393]
 [19.24830092]
 [34.82500273]
 [35.82313307]
 [31.98361387]
 [22.60816271]
 [16.00304541]
 [33.26518542]
 [11.8777567 ]
 [16.57261565]
 [15.37853666]
 [17.23824001]
 [12.56307998]
 [32.62663537]
 [27.47935773]
 [32.2568333 ]
 [33.46328054]
 [13.45512114]
 [10.84554166]
 [36.61828349]
 [15.94871002]
 [26.57263063]
 [14.47411481]
 [12.60985801]
 [15.03834361]
 [32.90535337]
 [25.47689898]
 [26.87662463]
 [36.49868477]
 [33.37604113]
 [39.98987183]
 [32.16996202]
 [18.40376

In [22]:
single_point = np.array(X_test)
result1 = np.dot(single_point, weight_hidden) + bias
result2 = ReLU(result1)
result3 = np.dot(result2, weight_hidden2) + bias1
result4 = ReLU(result3)
result5 = np.dot(result4, weight_hidden3) + bias2
result6 = ReLU(result5)
result7 = np.dot(result6, weight_hidden4) + bias3
result8 = ReLU(result7)
result9 = np.dot(result8, weight_hidden5) + bias4
result10 = ReLU(result9)
result11 = np.dot(result10, weight_output) + bias5
result12 = ReLU(result11)
print(result12)
print(Y_test)
print(len(X_test))
error_out = ((1/len(X_test)) * (np.power((result12 - Y_test), 2)))
print(math.sqrt(error_out.sum()))

[[15.18089687]
 [12.53017816]
 [14.2709088 ]
 [13.09017136]
 [14.77216214]
 [47.96013257]
 [17.03824716]
 [13.44075935]
 [28.16378929]
 [28.42534458]
 [10.46348327]
 [30.66921077]
 [15.07230825]
 [22.02291636]
 [19.52233332]
 [14.80782731]
 [28.37947319]
 [12.03596947]
 [13.40553197]
 [12.26873522]
 [38.24557199]
 [25.25661107]
 [33.95368265]
 [28.10876889]
 [23.60332629]
 [14.91618903]
 [16.13923093]
 [45.84329436]
 [11.09267596]
 [ 7.33499572]
 [10.7410216 ]
 [14.63786751]
 [26.82746611]
 [41.64246705]
 [26.52496621]
 [18.91311327]
 [34.21674144]
 [35.25678363]
 [31.43525021]
 [23.00943746]
 [15.47854438]
 [33.78047331]
 [11.57546676]
 [16.0292912 ]
 [13.8613924 ]
 [17.16898466]
 [12.02458814]
 [32.28570782]
 [27.12542669]
 [31.60482064]
 [33.66816282]
 [13.36046502]
 [10.45755661]
 [36.34124303]
 [15.44300497]
 [26.3316006 ]
 [14.26254832]
 [12.23878071]
 [14.75099394]
 [32.8302945 ]
 [25.37782975]
 [25.56918742]
 [34.68051192]
 [32.75089851]
 [38.36707891]
 [32.49881669]
 [17.13761